#pragma once
// =============================================================================
// ARC Raiders - Auto-Generated Decrypt Functions
// Generated by FrostDumper on Aug 18 2026 16:40:43
// Patch image size: 0x116E7000
// =============================================================================
//
// USAGE: #include this file. Provide ReadMemory(uint64_t addr, void* buf, size_t len)
//        and MODULE_BASE (e.g. 0x140000000 for Wine).
//
// All functions are standalone, no dependencies except <cstdint> and <cstring>.
// =============================================================================

#include <cstdint>
#include <cstring>

#ifndef MODULE_BASE
#define MODULE_BASE 0x140000000ULL
#endif

#ifndef READ_MEMORY
#error "Define READ_MEMORY(addr, buf, len) before including this file"
#endif

namespace ArcDecrypt {

// --- Helpers -----------------------------------------------------------------

static inline uint32_t Rotl32(uint32_t X, int N) { return (X << N) | (X >> (32 - N)); }
static inline uint64_t Rotl64(uint64_t X, int N) { return (X << N) | (X >> (64 - N)); }
static inline uint32_t Bswap32(uint32_t X) {
    return ((X >> 24) & 0xFF) | ((X >> 8) & 0xFF00) |
           ((X << 8) & 0xFF0000) | ((X << 24) & 0xFF000000);
}
static inline uint64_t Bswap64(uint64_t X) {
    X = ((X & 0x00000000FFFFFFFFULL) << 32) | ((X & 0xFFFFFFFF00000000ULL) >> 32);
    X = ((X & 0x0000FFFF0000FFFFULL) << 16) | ((X & 0xFFFF0000FFFF0000ULL) >> 16);
    X = ((X & 0x00FF00FF00FF00FFULL) << 8)  | ((X & 0xFF00FF00FF00FF00ULL) >> 8);
    return X;
}

static inline uint64_t SoftPshuflw(uint64_t V, int Imm) {
    uint16_t W[4];
    memcpy(W, &V, 8);
    uint16_t R[4] = {
        W[(Imm >> 0) & 3], W[(Imm >> 2) & 3],
        W[(Imm >> 4) & 3], W[(Imm >> 6) & 3]
    };
    uint64_t Out;
    memcpy(&Out, R, 8);
    return Out;
}

static inline void SoftPshufb8(uint8_t Out[8], const uint8_t In[8], const uint8_t Mask[8]) {
    for (int I = 0; I < 8; I++)
        Out[I] = (Mask[I] & 0x80) ? 0 : In[Mask[I] & 7];
}

// --- Constants (auto-discovered from binary) ---------------------------------

constexpr uint64_t GNAME_POOL_BASE    = 0xE4F2A00ULL;  // MODULE_BASE + this
constexpr uint64_t KEY_TABLE_RVA      = 0xE4317F4ULL;  // MODULE_BASE + this
constexpr uint64_t GWORLD_RVA         = 0xE782D78ULL;  // MODULE_BASE + this -> UWorld**
constexpr uint64_t GOBJECT_ARRAY_RVA  = 0xE64B260ULL;  // MODULE_BASE + this -> FChunkedFixedUObjectArray

// --- 1. UObject Slot Decode --------------------------------------------------
// Pipeline: ROL64(29) -> PSHUFLW(0x39) -> ROL32(5) -> extract lo64
// Input: 16 bytes from UObject + 0x20 (stride 0x20, 4 slots)
// Output: lo32 = ComparisonIndex, hi32 = FName::Number

static inline uint64_t DecryptUObjectSlot(const uint8_t Enc[16]) {
    uint64_t Lo, Hi;
    memcpy(&Lo, Enc, 8);
    memcpy(&Hi, Enc + 8, 8);
    Lo = Rotl64(Lo, 29);
    Hi = Rotl64(Hi, 29);
    Lo = SoftPshuflw(Lo, 0x39);
    uint32_t D0 = Rotl32((uint32_t)Lo, 5);
    uint32_t D1 = Rotl32((uint32_t)(Lo >> 32), 5);
    return (uint64_t)D0 | ((uint64_t)D1 << 32);
}

// --- 1b. QD-recorded UObject Slot Decode (generic, auto-recorded from binary) ---
static inline uint64_t DecryptUObjectSlot_QD(const uint8_t Enc[16]) {
    uint64_t Lo, Hi;
    memcpy(&Lo, Enc, 8);
    memcpy(&Hi, Enc + 8, 8);
    Lo = Rotl64(Lo, 50); Hi = Rotl64(Hi, 50);
    { uint32_t D0=Rotl32((uint32_t)Lo,22), D1=Rotl32((uint32_t)(Lo>>32),22),
               D2=Rotl32((uint32_t)Hi,22), D3=Rotl32((uint32_t)(Hi>>32),22);
      Lo=(uint64_t)D0|((uint64_t)D1<<32); Hi=(uint64_t)D2|((uint64_t)D3<<32); }
    return Lo;
}

// --- 2. UObject Slot Hash (selects which of 4 slots to read) ----------------
// FNV32-based, input is UObject address + 0x10

static inline int ComputeSlotIndex(uint64_t ObjAddr) {
    uint64_t P = ObjAddr + 0x10;
    uint32_t Lo = (uint32_t)P;
    uint32_t Hi = (uint32_t)(P >> 32);
    uint32_t H = Rotl32(Lo, 25) * 0x01000193u + 0xF3D8DA36u;
    H = Rotl32(H, 15) * 0x01000193u + Hi + 0xF3D8DA36u;
    H = Rotl32(H, 25) * 0x01000193u + 0xF3D8DA36u;
    H = Rotl32(H, 15) * 0x01000193u + 0xF3D8DA36u;
    return ((H ^ (H >> 16)) & 3) ^ 2;
}

static inline uint32_t GetUObjectCI(uint64_t ObjAddr) {
    int Slot = ComputeSlotIndex(ObjAddr);
    uint8_t Enc[16];
    READ_MEMORY(ObjAddr + 0x20 + Slot * 0x20, Enc, 16);
    return (uint32_t)DecryptUObjectSlot(Enc);
}

// --- 3. FField NamePrivate Decode --------------------------------------------
// Decrypts the encrypted ComparisonIndex stored at FField + 0xA0
// Pipeline: XOR64 -> ROL16(12) -> PSHUFB -> ROL64(32)

static inline uint32_t DecryptFFieldName(uint64_t Encrypted) {
    uint64_t V = Encrypted;
    V ^= 0x8FFAB191C340B792ULL;
    { uint16_t W[4]; memcpy(W, &V, 8);
      for (int I = 0; I < 4; I++) W[I] = (W[I] << 12) | (W[I] >> 4);
      memcpy(&V, W, 8); }
    { uint8_t Mask[8] = {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
      uint8_t In[8], Out[8]; memcpy(In, &V, 8);
      SoftPshufb8(Out, In, Mask); memcpy(&V, Out, 8); }
    V = Rotl64(V, 32);
    return (uint32_t)V;
}

// --- 4. FProperty Offset Decode ----------------------------------------------

static inline int32_t DecryptPropertyOffset(uint32_t Stored) {
    return (int32_t)(Bswap32(Stored) ^ 0x7BDAAA72u);
}

// --- 5. FName Resolution (ComparisonIndex -> string) -------------------------
// Shard hash: FNV32 with ROLs, slot-select formula: (-109*T+82) ^ ((P*T+ADD)>>16) & 7
// Block decode: ROL64(13) -> PSHUFLW(0x93) -> XOR
// FNV64 fold: ROL(37) + ADD, ROL(40) + ADD
// Pointer: 3-step bswap+XOR chain

static inline uint64_t FNameResolveEntry(uint32_t CI) {
    uint32_t NameOff = CI & 0xFFFF;
    uint32_t ChunkOff = (CI >> 8) & 0xFFFF00;
    uint64_t ChunkAddr = MODULE_BASE + GNAME_POOL_BASE + ChunkOff;

    // Shard hash
    uint64_t SeedAddr = ChunkAddr + 0x2F90ULL;
    uint32_t SeedLo = 0, SeedHi = 0;
    READ_MEMORY(SeedAddr, &SeedLo, 4);
    READ_MEMORY(SeedAddr + 4, &SeedHi, 4);
    uint32_t H = 0x01000193u * Rotl32(SeedLo, 17) + 0xD5AF8E52u;
    H = 0x01000193u * Rotl32(H, 13) + SeedHi + 0xD5AF8E52u;
    H = 0x01000193u * Rotl32(H, 17) + 0xD5AF8E52u;
    uint32_t T = Rotl32(H, 13);
    uint8_t Pa = (uint8_t)(-109 * T + 82);
    uint8_t Pb = (uint8_t)((0x01000193u * T + 0xD5AF8E52u) >> 16);
    int Bidx1 = (Pa ^ Pb) & 7;
    int Bidx2 = (Bidx1 + 1) & 7;

    // Block decode
    uint64_t BlockBase = ChunkAddr + 0x2FA0ULL;
    uint64_t Raw1 = 0, Raw2 = 0;
    READ_MEMORY(BlockBase + Bidx1 * 32, &Raw1, 8);
    READ_MEMORY(BlockBase + Bidx2 * 32, &Raw2, 8);
    uint64_t B1 = SoftPshuflw(Rotl64(Raw1, 13), 0x93) ^ 0x19EA7DF486E7194EULL;
    uint64_t B2 = SoftPshuflw(Rotl64(Raw2, 13), 0x93) ^ 0x19EA7DF486E7194EULL;

    // FNV64 chain
    uint64_t Fv1 = 0x100000001B3ULL * Rotl64(B1, 37) + 0x10F3A73711CE0312ULL;
    uint64_t Fv2 = 0x100000001B3ULL * Rotl64(Fv1, 40) + 0x10F3A73711CE0312ULL;
    uint64_t RawPtr = B1 + (B2 ^ Fv2) + 2 * NameOff;

    // Pointer XOR chain
    uint64_t Step1 = Bswap64(RawPtr ^ 0x0000000014329DBFULL);
    uint64_t Step2 = Step1 ^ 0x00002E3400000000ULL;
    uint64_t EntryPtr = Bswap64(Step2 ^ 0xBF9D1C2000000000ULL);
    return EntryPtr;
}

// --- 6. String Decrypt (FNameEntry -> readable string) -----------------------
// Header: length = hdr >> 6, isWide = (hdr & 0x20) != 0
// Key schedule: init = length + 0xA7B4, advance = key * 0x6DDC5690 + 0x5EBF2255

static inline int FNameDecryptString(uint64_t EntryPtr, char* OutBuf, int MaxLen) {
    uint16_t Hdr = 0;
    READ_MEMORY(EntryPtr, &Hdr, 2);
    int Length = Hdr >> 6;
    bool IsWide = (Hdr & 0x20) != 0;
    if (Length <= 0 || Length > MaxLen - 1) return 0;

    uint16_t KeyTable[64];
    READ_MEMORY(MODULE_BASE + KEY_TABLE_RVA + 0xE8, KeyTable, sizeof(KeyTable));

    if (!IsWide) {
        uint8_t Buf[1024];
        int ByteLen = Length * 2;
        if (ByteLen > 1024) ByteLen = 1024;
        READ_MEMORY(EntryPtr + 2, Buf, ByteLen);
        uint32_t Key = (uint32_t)(Length + 0xA7B4u);
        for (int I = 0; I < ByteLen; I += 2) {
            Buf[I]     ^= (uint8_t)(KeyTable[Key & 0x3Fu] >> 3);
            uint32_t Idx2 = (Key * 0xFFFF584Cu + 0xF629u) & 0x3Fu;
            if (I + 1 < ByteLen)
                Buf[I + 1] ^= (uint8_t)(KeyTable[Idx2] >> 3);
            Key = Key * 0x6DDC5690u + 0x5EBF2255u;
        }
        int OutLen = 0;
        for (int I = 0; I < ByteLen && OutLen < MaxLen - 1; I++) {
            if (Buf[I] >= 0x20 && Buf[I] < 0x7F)
                OutBuf[OutLen++] = (char)Buf[I];
        }
        OutBuf[OutLen] = 0;
        return OutLen;
    }
    return 0;
}

// --- 7. Full FName Resolve (CI -> string, convenience wrapper) ---------------

static inline int ResolveFName(uint32_t CI, char* OutBuf, int MaxLen) {
    if (CI == 0) { OutBuf[0] = 0; return 0; }
    uint64_t Entry = FNameResolveEntry(CI);
    if (Entry < 0x10000 || Entry > 0x7FFFFFFFFFFFULL) { OutBuf[0] = 0; return 0; }
    return FNameDecryptString(Entry, OutBuf, MaxLen);
}

// --- 7b. UWorld Access ------------------------------------------------------

static inline uint64_t GetUWorld() {
    uint64_t Ptr = 0;
    READ_MEMORY(MODULE_BASE + GWORLD_RVA, &Ptr, 8);
    return Ptr;
}

// --- 8. Player Name Decrypt (FNV-1a stream cipher) --------------------------
// Steam variant: UTF-16, single-round FNV-1a
// Constants from game binary (update per patch if changed):
//   InnerKey = FNV offset basis modifier
//   Rol32Key = ROL amount for hash mixing

static inline void DecryptPlayerName(uint16_t* S, int MaxChars,
                                      uint32_t InnerKey = 0x87400B27,
                                      int Rol32Key = 22) {
    if (!S || MaxChars < 2) return;
    uint16_t Ch = S[0];
    if (Ch == 0) return;
    int32_t V8 = 0;
    for (int I = 0; I < MaxChars && Ch != 0; I++) {
        int32_t Inner = 0x1000193 * V8 + (int32_t)InnerKey;
        int32_t Rotated = (int32_t)Rotl32((uint32_t)Inner, Rol32Key);
        int32_t V9 = V8 + Rotated;
        V8 = 0x1000193 * V9;
        int32_t V10 = Ch ^ ((-109 * (uint8_t)V9) & 0x1F);
        int32_t V11 = 0;
        if ((uint32_t)(V10 - 80) < 0x2F) V11 = -47;
        if ((uint32_t)(V10 - 33) < 0x2F) V11 = 47;
        uint32_t V12 = V11 + V10 - 48;
        uint32_t V13 = V11 + V10 - 53;
        int32_t V14 = V10 + V11;
        int32_t V15 = 5 * (V13 >= 5) - 5;
        if (V12 < 5) V15 = 5;
        int32_t V16 = V14 + V15;
        int32_t V17 = 0;
        if ((uint32_t)(V15 + V14 - 110) < 0xD) V17 = -13;
        if ((uint32_t)(V15 + V14 - 97) < 0xD) V17 = 13;
        int32_t V18 = V16 + V17;
        int32_t V19 = 0;
        if ((uint32_t)(V17 + V16 - 78) < 0xD) V19 = -13;
        if ((uint32_t)(V17 + V16 - 65) < 0xD) V19 = 13;
        uint32_t V20 = V19 + V18 - 33;
        uint32_t V21 = V19 + V18 - 80;
        int16_t V22 = (int16_t)(V18 + V19);
        int16_t V23 = 0;
        if (V21 < 0x2F) V23 = -47;
        if (V20 < 0x2F) V23 = 47;
        S[I] = (uint16_t)(V22 + V23);
        if (I + 1 < MaxChars) Ch = S[I + 1]; else break;
    }
}

// --- 9. Bone Array (USkeleton) ----------------------------------------------
// USkeleton::ReferenceSkeleton contains TArray<FMeshBoneInfo> (auto-probed).
// Each FMeshBoneInfo = { FName(CompIndex, Number), int32 ParentIndex } = 12 bytes.
// FNames resolve through the standard FName pipeline (no separate bone decrypt).
constexpr uint32_t USkeleton_BoneArrayOffset = 0xE8;
constexpr uint32_t BoneInfoStride            = 12;

// --- Layout Offsets ----------------------------------------------------------

namespace Offsets {
    constexpr uint32_t UObject_Slot0          = 0x20;
    constexpr uint32_t UObject_SlotStride     = 0x20;
    constexpr uint32_t UStruct_SuperStruct    = 0xB0;
    constexpr uint32_t UStruct_ChildProperties = 0xF8;
    constexpr uint32_t UStruct_PropertiesSize = 0x108;
    constexpr uint32_t FField_NamePrivate     = 0x50;
    constexpr uint32_t FField_Next            = 0x60;
    constexpr uint32_t FField_Owner           = 0x80;
    constexpr uint32_t FField_ClassPrivate    = 0x70;
    constexpr uint32_t FProperty_Offset       = 0xA4;
    constexpr uint32_t FProperty_ElementSize  = 0xD8;
    constexpr uint32_t FProperty_ArrayDim     = 0xD0;
    constexpr uint32_t FStructProperty_Struct = 0x100;
    constexpr uint32_t FObjectProperty_Class  = 0x100;
    constexpr uint32_t FBoolProperty_FieldSize = 0x100;
    constexpr uint32_t FArrayProperty_Inner   = 0x108;
    constexpr uint32_t UFunction_NativeFunc   = 0x150;
} // namespace Offsets

} // namespace ArcDecrypt
